/* Original learning items. The band and taxonomy describe the task students actually do. */
(() => {
  const make = (id, band, objective, process, knowledge, ao, term, difficulty, format, prompt, answer, points, extra = {}) => ({
    id, curriculumBand: band, objective, bloomProcess: process, knowledgeType: knowledge,
    cambridgeAO: ao, commandTerm: term, difficulty, format, prompt, answer,
    marks: points.length, markPoints: points, ...extra,
  });
  const C = 'igcse-core', S = 'igcse-supplement', I = 'beyond-igcse-ib', B = 'beyond-ib';
  const questions = [
    make('C01',C,'5.2.1','remember','factual','AO1','define',1,'choice','What is background radiation?',1,['Ionising radiation present in the environment even without the source being tested.'],{options:['Radiation only from a laboratory source','Ionising radiation normally present in the environment','Heat emitted by the detector','Radiation made by the counter']}),
    make('C02',C,'5.2.1','remember','factual','AO1','identify',1,'choice','Which source is a significant contributor to natural background radiation?',2,['Radon gas in the air.'],{options:['A switched-off lamp','A wooden ruler','Radon gas in the air','A digital stopwatch']}),
    make('C03',C,'5.2.1','remember','factual','AO1','state',2,'structured','Name two sources of background radiation other than radon gas.','Rocks and building materials, food and drink, and cosmic rays are possible sources.',['One of: rocks/buildings, food/drink, cosmic rays.','A second, different source from the same list.'],{allowAlternatives:true}),
    make('C04',C,'5.2.1','remember','factual','AO1','state',1,'choice','What arrangement can measure ionising nuclear radiation?',0,['A detector connected to a counter.'],{options:['A detector connected to a counter','A thermometer connected to a timer','A lens connected to a screen','A magnet connected to a spring']}),
    make('C05',C,'5.2.1','apply','procedural','AO2','calculate',2,'number','A counter records 84 counts in 2 minutes. Calculate the mean count rate in counts per minute.',42,['Divide 84 counts by 2 minutes.','42 counts per minute.'],{unit:'counts/min'}),
    make('C06',C,'5.2.1','apply','procedural','AO2','calculate',2,'number','With a source present, a counter reads 126 counts/min. Background alone is 18 counts/min. Calculate the corrected count rate.',108,['Subtract background from the measured rate.','108 counts/min.'],{unit:'counts/min'}),
    make('C07',C,'5.2.2','understand','conceptual','AO1','explain',2,'structured','Equal-time measurements of one unchanged radioactive source give slightly different counts. Explain why.','Decay events are random, so equal intervals need not contain identical numbers of events.',['Radioactive emissions occur randomly.','Different equal intervals can contain different numbers of emissions.']),
    make('C08',C,'5.2.2','remember','factual','AO1','state',1,'choice','Which description fits radioactive emission from an unstable nucleus?',1,['Emission is spontaneous and random.'],{options:['It waits for the observer to start the counter','It is spontaneous and random','Each nucleus emits at a scheduled time','It is caused by the chamber light']}),
    make('C09',C,'5.2.2','remember','factual','AO1','state',1,'choice','What is an alpha particle?',0,['A helium nucleus containing two protons and two neutrons.'],{options:['A helium nucleus with two protons and two neutrons','A high-speed electron','A high-frequency electromagnetic wave','A neutron by itself']}),
    make('C10',C,'5.2.2','remember','factual','AO1','state',1,'choice','In this IGCSE topic, what is a beta particle?',2,['A high-speed electron emitted from the nucleus.'],{options:['A helium nucleus','A gamma photon','A high-speed electron emitted from the nucleus','A proton emitted from the nucleus']}),
    make('C11',C,'5.2.2','remember','factual','AO1','state',1,'choice','What is gamma radiation?',3,['High-frequency electromagnetic radiation.'],{options:['A stream of helium nuclei','A stream of electrons','A stream of neutrons','High-frequency electromagnetic radiation']}),
    make('C12',C,'5.2.2','understand','conceptual','AO1','compare',2,'order','Arrange alpha, beta and gamma from greatest to least ionising effect.',['Alpha','Beta','Gamma'],['Alpha has the greatest relative ionising effect.','Beta is intermediate.','Gamma has the least relative ionising effect.'],{options:['Gamma','Alpha','Beta']}),
    make('C13',C,'5.2.2','understand','conceptual','AO1','compare',2,'order','Arrange alpha, beta and gamma from least to greatest penetrating ability.',['Alpha','Beta','Gamma'],['Alpha is least penetrating.','Beta is intermediate.','Gamma is most penetrating.'],{options:['Beta','Gamma','Alpha']}),
    make('C14',C,'5.2.2','apply','conceptual','AO2','identify',2,'track','A simulated chamber shows three candidate trails. Select the one most consistent with an alpha particle.',0,['Select the short, dense trail.'],{options:['Short, dense trail','Fine, irregular trail','Long, nearly straight trail'],trackTypes:['alpha','beta','muon']}),
    make('C15',C,'5.2.2','analyze','conceptual','AO2','compare',3,'compare','Trail A is short and made of closely packed droplets. Trail B is longer and thinner. Compare their likely ionisation and penetration.','A is more strongly ionising and less penetrating than B.',['Trail A indicates denser ionisation.','Trail A is likely less penetrating.','Trail B indicates weaker ionisation and greater penetration.'],{figure:{type:'trails',labels:['A: short, dense','B: long, fine']}}),
    make('C16',C,'5.2.2','understand','conceptual','AO1','explain',2,'structured','Why does a gamma ray not normally draw a continuous direct trail like an alpha particle in a cloud chamber?','Gamma radiation has no electric charge, so it does not directly ionise a continuous path in the same way; it can create a secondary charged particle.',['Gamma radiation is uncharged.','It does not directly produce the same continuous ionisation trail; a secondary electron may be seen.']),
    make('C17',C,'5.2.2','apply','conceptual','AO2','predict',1,'choice','A thin sheet of paper is placed between an alpha source and a detector. What happens to the alpha count?',0,['The count falls greatly because paper absorbs alpha particles.'],{options:['It falls greatly','It doubles','It is unchanged for every alpha particle','It becomes a gamma count']}),
    make('C18',C,'5.2.2','apply','conceptual','AO2','suggest',2,'structured','A source emits beta radiation. Suggest a material that can reduce the beta count and explain why.','A few millimetres of aluminium absorb many beta particles because beta is more penetrating than alpha but less than gamma.',['Aluminium or another suitable beta absorber.','It absorbs beta particles, reducing the detected rate.']),
    make('C19',C,'5.2.2','understand','conceptual','AO1','compare',2,'choice','Which pairing of radiation and suitable shielding is most sensible?',2,['Thick lead for gamma radiation.'],{options:['Paper for gamma','Air only for gamma','Thick lead for gamma','A thin plastic film for all radiation']}),
    make('C20',C,'5.2.4','remember','conceptual','AO1','define',1,'choice','What is the half-life of an isotope?',1,['The time taken for half the nuclei of that isotope in a sample to decay.'],{options:['The time for one particular nucleus to decay','The time for half the nuclei in a sample to decay','The time for all nuclei in a sample to decay','Half the lifetime of the detector']}),
    make('C21',C,'5.2.4','apply','procedural','AO2','determine',2,'graph','Use the decay graph. The number of undecayed nuclei falls from 80 to 20 in 12 hours. Determine the half-life.',6,['80 → 40 → 20 is two half-lives.','12 hours ÷ 2 = 6 hours.'],{unit:'hours',figure:{type:'graph',headings:['Time / h','Nuclei remaining'],rows:[[0,80],[6,40],[12,20],[18,10]]}}),
    make('C22',C,'5.2.3','remember','conceptual','AO1','state',1,'choice','What happens to the element when its nucleus undergoes alpha or beta decay?',2,['The nucleus becomes that of a different element.'],{options:['Only its temperature changes','Its chemical symbol must stay the same','It becomes a different element','Its electrons stop moving']}),
    make('C23',C,'5.2.5','remember','factual','AO1','state',2,'structured','State two possible biological effects of ionising radiation.','Cell death, mutations and cancer are possible effects.',['One of: cell death, mutation, cancer.','A second, different effect from the same list.'],{allowAlternatives:true}),
    make('C24',C,'5.2.5','apply','procedural','AO3','describe',2,'structured','A technician must move a sealed radioactive source across a room. Describe two safe handling choices.','Use tongs or remote handling and keep the source in suitable shielding when it is not in use.',['Use tongs or remote handling to increase separation.','Keep the source shielded or minimise handling time.'],{allowAlternatives:true}),
    make('C25',C,'5.2.1','analyze','procedural','AO3','justify',2,'structured','A counter gives 4 counts in 5 s on one trial. Why is a single 5 s reading weak evidence of the source rate? Suggest one improvement.','Random fluctuations have a large relative effect on a small count; count for longer or repeat equal-time readings.',['Small counts have substantial relative random variation.','Use a longer interval or repeat and average equal-time readings.'],{allowAlternatives:true}),
    make('C26',C,'5.2.1','apply','procedural','AO3','describe',3,'structured','Design a fair comparison of the count rate with and without a source using one counter.','Use the same counter position and equal counting times; repeat readings and subtract the background rate.',['Keep detector position and counting interval the same.','Take repeated readings in each condition.','Calculate rates and subtract background from the source-present rate.']),
    make('C27',C,'5.2.2','analyze','conceptual','AO2','deduce',2,'evidence','A short, thick trail appears among several fine trails. Select the two observations that best support an alpha inference.',[0,2],['Its droplets are densely packed.','Its trail is short compared with the fine trails.'],{options:['Droplets are densely packed','The chamber has a blue border','The trail is relatively short','The counter has a digital display']}),
    make('C28',C,'5.2.1','apply','procedural','AO2','calculate',2,'number','A detector reads 30 counts/min with a sample and 27 counts/min without it. What is the corrected rate?',3,['Subtract the without-sample rate as background.','30 − 27 = 3 counts/min.'],{unit:'counts/min'}),

    make('S29',S,'5.2.2','apply','conceptual','AO2','predict',2,'structured','In an electric field, an alpha particle and a beta-minus particle pass between oppositely charged plates. Predict their directions of deflection.','Alpha bends toward the negative plate; beta-minus bends toward the positive plate.',['Alpha, being positive, bends toward the negative plate.','Beta-minus, being negative, bends toward the positive plate.']),
    make('S30',S,'5.2.2','understand','conceptual','AO1','explain',2,'structured','Explain why an alpha particle is usually more ionising than a beta-minus particle.','Alpha has a larger electric charge and can transfer energy to more atoms along a short route.',['Alpha has charge +2e, greater in magnitude than beta-minus charge −e.','Its interactions transfer energy and make dense ionisation.']),
    make('S31',S,'5.2.2','understand','conceptual','AO1','identify',2,'incorrect','Which statement about a beta-minus particle is incorrect?',1,['The two-protons/two-neutrons statement describes alpha, not beta-minus.'],{options:['It is a high-speed electron','It contains two protons and two neutrons','It can be deflected in a field','It is usually less ionising than alpha']}),
    make('S32',S,'5.2.3','understand','conceptual','AO1','explain',2,'structured','Why can an isotope of a familiar element still be radioactive?','Its nucleus may have too many neutrons or be too heavy to remain stable.',['The isotope has a different neutron number.','An excess of neutrons or a very heavy nucleus can make it unstable.']),
    make('S33',S,'5.2.3','apply','procedural','AO2','determine',3,'structured','Uranium-238 (Z = 92) emits an alpha particle and becomes thorium (Th). Write the balanced decay equation in nuclide notation.','<sup>238</sup><sub>92</sub>U → <sup>234</sup><sub>90</sub>Th + <sup>4</sup><sub>2</sub>He.',['Daughter mass number is 234.','Daughter proton number is 90.','The alpha particle is <sup>4</sup><sub>2</sub>He; both numbers balance.']),
    make('S34',S,'5.2.3','apply','procedural','AO2','determine',3,'structured','Carbon-14 (Z = 6) emits a beta-minus particle and becomes nitrogen (N). Write the balanced decay equation in nuclide notation.','<sup>14</sup><sub>6</sub>C → <sup>14</sup><sub>7</sub>N + <sup>0</sup><sub>−1</sub>e.',['Daughter mass number remains 14.','Daughter proton number rises to 7.','The beta-minus particle is <sup>0</sup><sub>−1</sub>e; both numbers balance.']),
    make('S35',S,'5.2.3','understand','conceptual','AO1','describe',2,'structured','Describe the change in mass number and proton number when a nucleus emits only gamma radiation.','Neither number changes; gamma emission releases energy from the nucleus.',['Mass number does not change.','Proton number does not change.']),
    make('S36',S,'5.2.4','analyze','procedural','AO2','determine',3,'data','A detector measures a source at 100, 60 and 40 counts/min at 0, 5 and 10 minutes. Background is 20 counts/min. Determine the half-life.','The corrected rates are 80, 40 and 20 counts/min, halving every 5 minutes.',['Subtract 20 counts/min from each reading.','Corrected rates are 80, 40 and 20 counts/min.','Half-life is 5 minutes.'],{figure:{type:'table',headings:['Time / min','Measured / counts min⁻¹'],rows:[[0,100],[5,60],[10,40]]}}),
    make('S37',S,'5.2.4','evaluate','conceptual','AO2','justify',3,'structured','A smoke alarm uses an alpha source. Justify alpha rather than gamma for this design.','Alpha ionises air inside the alarm; smoke reduces the current, and the weakly penetrating alpha source can be contained by the casing.',['Alpha strongly ionises air.','Smoke changes the ionisation/current so the alarm can detect it.','Alpha is weakly penetrating and can be contained by the casing.']),
    make('S38',S,'5.2.4','apply','conceptual','AO2','suggest',2,'structured','A factory wants to sterilise sealed medical equipment. Suggest a type of radiation and give a reason.','Gamma radiation can penetrate the packaging and kill microorganisms.',['Choose gamma radiation.','It penetrates packaging and ionisation can kill microorganisms.']),
    make('S39',S,'5.2.4','evaluate','conceptual','AO2','justify',3,'structured','A beta source and counter monitor thin plastic sheet thickness. Explain why beta is more suitable than alpha or gamma.','Some beta passes through thin plastic and is absorbed more as thickness rises; alpha would be stopped too readily, gamma too little.',['Some beta passes through the sheet to the detector.','Thicker sheet absorbs more beta, changing the count.','Alpha is too easily stopped or gamma too penetrating for this thin sheet.'],{allowAlternatives:true}),
    make('S40',S,'5.2.5','apply','procedural','AO3','explain',3,'structured','A worker must briefly inspect a gamma source. Explain three ways to reduce exposure.','Minimise time near it, increase distance and use suitable shielding.',['Reduce time near the source.','Increase distance from the source.','Use suitable shielding.']),

    make('I41',I,'IB D.2','understand','conceptual',null,'compare',2,'structured','A nucleus decays once but a detector registers no count. Explain why activity and measured count rate are different.','Activity counts all decays; the detector records only emissions that reach and register in it.',['Activity is decays per second in the source.','Count rate includes only detected events and depends on detector efficiency or geometry.'],{allowAlternatives:true}),
    make('I42',I,'IB D.2','analyze','conceptual',null,'deduce',3,'structured','Two isotopes have the same proton number. One has many extra neutrons and decays. Distinguish their identity from their stability.','They are the same element but different isotopes; a different neutron-to-proton balance can make one unstable.',['Same proton number means same element.','Different neutron numbers mean different isotopes.','The changed neutron balance can affect nuclear stability.']),
    make('I43',I,'IB D.2','understand','conceptual',null,'explain',3,'structured','A bound nucleus has less mass than its separate nucleons. What does that mass difference represent?','The mass defect corresponds to binding energy released when the nucleus forms.',['Identify the difference as mass defect.','Its energy equivalent is nuclear binding energy.','Energy was released when the nucleons became bound.']),
    make('I44',I,'IB D.2','apply','procedural',null,'calculate',2,'number','A nuclear process has mass defect 2.0 × 10⁻²⁹ kg. Using c = 3.0 × 10⁸ m/s, calculate the energy equivalent in joules.',1.8e-12,['Use E = mc².','E = 1.8 × 10⁻¹² J.'],{unit:'J',tolerance:1e-13}),
    make('I45',I,'IB D.2','understand','conceptual',null,'explain',2,'structured','Protons repel electrically. Why can they remain together in a nucleus?','The short-range strong nuclear force attracts nucleons strongly enough at nuclear distances to overcome the electrical repulsion.',['Protons electrically repel.','At nuclear distances the strong nuclear force is attractive and can overcome that repulsion.']),
    make('I46',I,'IB D.2','apply','procedural',null,'determine',2,'structured','A nucleus emits a beta-plus particle. Predict the change in proton number and mass number.','Proton number decreases by one; mass number stays the same.',['Proton number decreases by one.','Mass number is unchanged.']),
    make('I47',I,'IB D.2','understand','conceptual',null,'state',2,'choice','Which additional particle accompanies beta-minus decay in a fuller nuclear equation?',3,['An electron antineutrino.'],{options:['An alpha particle','A second electron','A gamma ray in every decay','An electron antineutrino']}),
    make('I48',I,'IB D.2','analyze','conceptual',null,'explain',3,'structured','One nucleus has an unpredictable decay time, yet a large sample gives a smooth half-life curve. Explain both claims.','Each nucleus decays randomly; a very large population follows stable statistical proportions over time.',['An individual decay time is random and cannot be predicted.','Many nuclei provide a large statistical sample.','The fraction remaining follows a predictable pattern.']),
    make('I49',I,'IB D.2','evaluate','procedural',null,'comment',3,'data','A counter records 41, 38, 45 and 40 counts in four equal intervals. A student says the source activity is changing. Assess this claim.','These small differences are consistent with random counting variation; more readings are needed before claiming a trend.',['The readings differ but have no consistent trend.','Random decay/counting variation can explain such differences.','Repeat more equal-time measurements before claiming changing activity.'],{figure:{type:'table',headings:['Interval','Counts'],rows:[[1,41],[2,38],[3,45],[4,40]]}}),
    make('I50',I,'CLOUD MORE','analyze','conceptual',null,'deduce',2,'choice','A gamma ray enters a cloud chamber. A short electron-like trail begins nearby. What is the cautious inference?',1,['The gamma ray may have transferred energy to an electron, which made the visible trail.'],{options:['The gamma ray itself drew a charged line','A secondary electron may have made the trail','The gamma ray became an alpha particle','The trail proves the photon path exactly']}),
    make('I51',I,'CLOUD MORE','understand','conceptual',null,'define',2,'structured','In a diffusion cloud chamber, what does supersaturated vapour mean?','The vapour is in a state where condensation is favourable if a suitable seed is available.',['There is more vapour than would remain stable at that local temperature.','A suitable seed can start condensation.']),
    make('I52',I,'CLOUD MORE','understand','conceptual',null,'explain',3,'structured','Why do droplets form along a charged particle route instead of evenly everywhere?','The particle ionises molecules along its route; ions provide seeds for condensation in supersaturated vapour.',['The charged particle ionises molecules along a route.','The resulting ions are local condensation seeds.','Droplets reveal that route rather than filling the chamber uniformly.']),
    make('I53',I,'CLOUD MORE','analyze','conceptual',null,'explain',3,'compare','Two fine charged-particle trails differ: one nearly straight, one strongly irregular. Suggest a reason without claiming exact particle identity.','A lower-momentum light charged particle may scatter more readily; track appearance alone does not determine its exact origin.',['The irregular trail shows more changes in direction.','A light charged particle with lower momentum scatters more readily.','Appearance alone does not prove the origin or identity.'],{figure:{type:'trails',labels:['A: almost straight','B: irregular']}}),
    make('I54',I,'CLOUD MORE','apply','conceptual',null,'suggest',2,'structured','A very long, fine, almost straight trail crosses the whole chamber. Suggest a plausible particle and state one limit of this inference.','A cosmic-ray muon is plausible, but a track shape alone is not conclusive.',['A cosmic-ray muon is plausible.','A similar trail could be made by another fast charged particle; appearance is not proof.']),
    make('I55',I,'IB D.2','evaluate','metacognitive',null,'justify',3,'structured','A student says: “I saw the particle itself.” Another says: “I saw droplets linked to its passage.” Which is better supported? Justify.','The second claim is better supported: the observation is droplets, with a charged route inferred from ionisation.',['Prefer the droplets claim.','The direct observation is a condensation trail.','The particle route and identity are inferences with limits.']),
    make('I56',I,'IB D.2','analyze','procedural',null,'determine',3,'number','An isotope has half-life 4 h. A counter initially reads 144 counts/s, including background of 16 counts/s. If geometry is unchanged, predict its total reading after 12 h.',32,['Initial corrected rate is 144 − 16 = 128 counts/s.','After three half-lives it is 128 ÷ 8 = 16 counts/s.','Add unchanged background: total is 32 counts/s.'],{unit:'counts/s'}),
    make('B57',B,'IB HL','apply','procedural',null,'calculate',2,'number','A nuclide has half-life 10 s. Calculate its decay constant λ in s⁻¹ using ln 2 = 0.693.',0.0693,['Use λ = ln 2 / T½.','λ = 0.0693 s⁻¹.'],{unit:'s⁻¹',tolerance:0.002}),
    make('B58',B,'CURIOUS PHYSICS','analyze','conceptual',null,'deduce',3,'structured','Two charged particles enter the same uniform magnetic field in the same direction, but their tracks curve to opposite sides. What can you infer, and what cannot you infer from curvature alone?','Opposite curvature suggests opposite charge signs; curvature alone does not uniquely name the particles.',['Opposite bending supports opposite charge signs.','Field direction must be known to assign the signs.','Curvature alone does not uniquely identify either particle.']),
    make('B59',B,'CURIOUS PHYSICS','evaluate','conceptual',null,'justify',3,'structured','A historical cloud-chamber photograph shows a track crossing a lead plate and bending more tightly on one side in a known magnetic field. Why was this stronger positron evidence than an isolated curved line?','The lead plate showed energy loss and hence travel direction; the field and bending then supported positive charge. Combining clues strengthened the positron inference.',['Greater curvature after the plate indicates energy loss and helps establish travel direction.','Bending in the known magnetic field supports positive charge.','Combining charge and direction clues is stronger than one curve alone.']),
    make('B60',B,'CURIOUS PHYSICS','create','metacognitive',null,'design',4,'structured','Design a short simulation investigation to test whether long, straight trails are a reliable clue for cosmic muons rather than electrons.','Collect repeated single-source samples for each type, define length and straightness criteria before viewing results, compare frequencies and state that the simulation model limits any real-world conclusion.',['Set a testable comparison and define length/straightness criteria.','Collect repeated equal-condition samples for muons and electrons.','Compare the frequency meeting the criteria, not one example.','State the model/track-overlap limitation of the conclusion.'],{useSimulator:true}),
  ];

  const more = {
    see: [
      {title:'How does a line appear?',text:'Above a cold base, alcohol vapour can be ready to condense. A passing charged particle makes ions; those ions seed tiny droplets along its route.'},
      {title:'We see effects, not particles',text:'The visible line is droplets. A particle path and identity are inferences from that evidence, and several particles can make similar-looking trails.'},
    ],
    identify: [
      {title:'Why are beta trails less tidy?',text:'Electrons are light. Collisions can change their direction, especially when their momentum is low. A fine irregular route is a clue, not a fingerprint.'},
      {title:'The long straight stranger',text:'Cosmic rays can produce muons high in the atmosphere. A fast muon may cross the whole chamber as a long, fine trail.'},
    ],
    explain: [
      {title:'Why does alpha ionise so densely?',text:'An alpha particle carries twice the elementary charge magnitude of a beta-minus particle and interacts strongly over a short route, losing energy to nearby atoms.'},
      {title:'Where does nuclear energy fit?',text:'Binding energy is the energy needed to separate a nucleus into its nucleons. The bound nucleus has a mass defect: energy and mass are linked by E = mc².'},
    ],
    predict: [
      {title:'What about gamma?',text:'Gamma radiation is an uncharged electromagnetic wave. It does not directly draw the same kind of line, but it can transfer energy to an electron that then leaves a trail.'},
      {title:'A magnetic-field clue',text:'A magnetic field can bend charged tracks. Opposite charge signs bend oppositely under comparable conditions; lower momentum usually means stronger curvature.'},
    ],
    measure: [
      {title:'Activity is not count rate',text:'Activity is decays per second in the source. A counter records only events that reach and register in the detector, so geometry and efficiency matter.'},
      {title:'Random individuals, steady crowds',text:'No one nucleus has a predictable decay time. For a large population, the fraction remaining follows a reliable statistical pattern.'},
    ],
    data: [
      {title:'Beyond whole half-lives',text:'At IB higher level, the number remaining can be modelled by N = N₀e^(−λt), with T½ = ln(2)/λ. The curve is smooth for a large sample.'},
      {title:'Why a beta energy spectrum is continuous',text:'In beta decay, energy is shared with an (anti)neutrino. Electrons can emerge with a range of energies rather than one fixed value.'},
    ],
    apply: [
      {title:'An unfamiliar track',text:'A long, nearly straight trail could be a cosmic muon, but a fast electron can look similar. Ask what was observed, what was inferred, and what other evidence could help.'},
      {title:'A surprising discovery',text:'Cloud-chamber photographs in a magnetic field helped reveal the positron. Opposite curvature to an electron was an important clue to opposite charge.'},
    ],
  };

  const activities = [
    {id:'A-SEE',step:'see',curriculumBand:C,bloomProcess:'remember',knowledgeType:'conceptual',cambridgeAO:'AO2',commandTerm:'identify',marks:1,difficulty:1,objective:'5.2.2'},
    {id:'A-IDENTIFY',step:'identify',curriculumBand:C,bloomProcess:'analyze',knowledgeType:'conceptual',cambridgeAO:'AO2',commandTerm:'deduce',marks:2,difficulty:2,objective:'5.2.2'},
    {id:'A-EXPLAIN',step:'explain',curriculumBand:C,bloomProcess:'understand',knowledgeType:'conceptual',cambridgeAO:'AO1',commandTerm:'explain',marks:2,difficulty:2,objective:'5.2.2'},
    {id:'A-PREDICT',step:'predict',curriculumBand:C,bloomProcess:'apply',knowledgeType:'conceptual',cambridgeAO:'AO2',commandTerm:'predict',marks:2,difficulty:2,objective:'5.2.2'},
    {id:'A-MEASURE',step:'measure',curriculumBand:C,bloomProcess:'analyze',knowledgeType:'procedural',cambridgeAO:'AO3',commandTerm:'comment',marks:2,difficulty:3,objective:'5.2.1'},
    {id:'A-DATA',step:'data',curriculumBand:C,bloomProcess:'apply',knowledgeType:'procedural',cambridgeAO:'AO2',commandTerm:'calculate',marks:2,difficulty:2,objective:'5.2.1'},
    {id:'A-APPLY',step:'apply',curriculumBand:C,bloomProcess:'evaluate',knowledgeType:'metacognitive',cambridgeAO:'AO2',commandTerm:'justify',marks:2,difficulty:3,objective:'5.2.2'},
  ];

  const units = [
    {id:'see',title:'SEE',heading:'Notice the evidence',summary:'Watch a fresh alpha-and-beta sample. Look for differences in trail length and droplet density.'},
    {id:'identify',title:'IDENTIFY',heading:'Make a cautious identification',summary:'A single unknown trail appears. Predict its most likely source before you reveal the model’s answer.'},
    {id:'explain',title:'EXPLAIN',heading:'Connect trail to ionisation',summary:'Use observations to support a physics explanation. A trail is a clue, not a certain fingerprint.'},
    {id:'predict',title:'PREDICT',heading:'Change the particle mix',summary:'Predict the effect of leaving only alpha events on, then run the chamber and compare.'},
    {id:'measure',title:'MEASURE',heading:'Collect equal-time counts',summary:'Use a virtual counter beside the chamber. Repeat readings to see random variation and background.'},
    {id:'data',title:'USE DATA',heading:'Correct a count rate',summary:'Measure background and source-present counts for equal times, then subtract the background rate.'},
    {id:'apply',title:'APPLY',heading:'Reason from unfamiliar evidence',summary:'Use absorber data to infer a likely emission and choose the observation that supports it.'},
  ];

  const content = {questions,more,activities,units};
  globalThis.CloudChamberContent = content;
  if (typeof module !== 'undefined' && module.exports) module.exports = content;
})();
